### ISSUE TITLE
Crash in local call

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/cppTango#328]
Hello. We've stumbled upon another crash that happens with a local-call from a thread - not unlike my previous bug (823). I applied the patch to blackbox.cpp, but now I get a crash that does not go through the blackbox:

~~~
#0 0x00007ffff1e1ce62 in omni_thread::get_value (this=0x0, k=2) at threaddata.cc:71
#1 0x00007ffff3e9defa in Tango::DeviceImpl::get_client_ident (this=<optimized out>) at device.cpp:4416
#2 0x00007ffff3ea5255 in Tango::DeviceImpl::check_lock (this=this@entry=0x2007850, meth=meth@entry=0x7ffff40991a5 "command_inout4",
cmd=cmd@entry=0x7fff94005eb8 "Stop") at device.cpp:4820
#3 0x00007ffff3ed3ee2 in Tango::Device_4Impl::command_inout_4 (this=0x2007850, in_cmd=0x7fff94005eb8 "Stop", in_data=..., source=Tango::CACHE_DEV, cl_id=...)
at device_4.cpp:467
#4 0x00007ffff404f342 in _0RL_lcfn_6fe2f94a21a10053_a3000000 (cd=0x7fffa2ff8dc0, svnt=<optimized out>) at tangoSK.cpp:5383
#5 0x00007ffff38bd333 in doLocalCall (servant=<optimized out>, this=0x7fffa2ff8dc0) at ../../../../include/omniORB4/callDescriptor.h:145
#6 omni::omniOrbPOA::dispatch (this=<optimized out>, call_desc=..., id=0x26924b0) at poa.cc:1852
#7 0x00007ffff389e6ee in omniLocalIdentity::dispatch (this=0x26924b0, call_desc=...) at localIdentity.cc:145
------------SNIP--------------
#142 0x00007ffff78180db in start_thread () from /lib64/libpthread.so.0
#143 0x00007ffff7548e3d in clone () from /lib64/libc.so.6
~~~

Johan here https://sourceforge.net/p/tango-cs/bugs/814/#da32 seems to have the same problem.

Reported by: schneidemwe ( http://sf.net/u/schneidemwe )

Original Ticket: [tango-cs/bugs/827](https://sourceforge.net/p/tango-cs/bugs/827)

**Comment by bourtemb** [comment]
Problem solved in Tango 9.2.5, even though the solution re-introduced a small memory leak.
